server:
  port: 8093

spring:
  application:
    name: GATEWAY
  cloud:
    consul:
      host: localhost
      port: 8500

    gateway:
      routes:
        - id: category_router #路由对象唯一标识
#          uri: http://localhost:8086/ #类别服务地址
          uri: lb://CATEGORY
          predicates: #断言 用来配置路由规则
            - Path=/getCategory
        - id: product_router #路由对象唯一标识
#          uri: http://localhost:8089/ #类别服务地址
          uri: lb://PRODUCT # 请求负载均衡
          predicates: #断言 用来配置路由规则
            - Path=/product/**
